### ISSUE TITLE
MVP Proposal Comments

### ISSUE THREAD

**Issue by loschorts** [Tonyhliu/Sideline#1]
Hey Tony, 

Great job! I think you have a solid foundation. Please see my comments below. 
- I think having a more robust sign-up feature would help: Medium forces you to pick which topics to follow and suggests some people to follow. That would make your site more interesting to someone than a simple "guest" account.
- I would allocate 2 days for Front-End Auth. It's trickier than you think and it's crucial to your app.
- You need to do Webpack/Flux setup in Phase 1(Auth). You'll also need to set up your API for that.
- I don't think the Medium API is going to allow you to fetch stories en masse. You'll have to do something like [this](https://medium.com/@sprawsmdoo/post-medium-articles-to-your-website-with-jquery-and-kimono-6fd9b276fca2#.z5pw9fpdw).
- You should be doing basic styling at every step: layout / display / functionality (hiding, scrolling etc). The rest (color scheme, borders, etc.) can wait until later.
- What is the difference between a `like` and a `follow`?
- A better MVP feature would be `tags`, that way your search bar can filter by sport / team / athlete / whatever. I suggest replacing the `like` feature with `tags`, but it's up to you.
- Definitely include an image upload / banner image for posts. Otherwise, your site will lack visual appeal.
- A signup modal is a good idea, but I think you should budget a little more time for it.
- I think your `StoryForm` should live on a separate route, i.e. tony.com/new and tony.com/story/1/edit.

**Comment by Tonyhliu** [comment]
Ken,

Thanks for the feedback. I just updated my timeline along with 2 more new wireframes. I went ahead and drew out a wireframe of what it should look like after a user signs up (I went with how they'll be able to choose what sports interests them instead of who to follow). & What did you mean by my StoryForm should live on a separate route? Lmk

But besides that, I'm nervous yet excited to get started!
